name: Custom Dependabot 
# Update Docker Base Images, append changelogs and bump addon patch version
on: 
  schedule:
    - cron: "0 14 * * 0"
  workflow_dispatch:

jobs:
  Dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install perquisite
        run: |
          pip3 install dockerfile-parse
      - name: Scan for deprecated base images
        run: |
          python3 ./.github/resources/custom_dependabot
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git commit -a -m "Updated base images"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4