name: Custom Dependabot 
# Update Docker Base Images, append changelogs and bump addon patch version
on: 
  schedule:
    - cron: "0 14 * * 0"
  workflow_dispatch:

jobs:
  Dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Install perquisite
        run: |
          pip3 install dockerfile-parse
      - name: Checkout Repo
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          REPO_URL=https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git clone "${REPO_URL}" .
      - name: Scan for deprecated base images
        run: |
          python3 ./.github/resources/custom_dependabot
      - name: Push changes
        run: |
          if ! [ -z "$(git status --porcelain)" ]; then 
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action Bot"
            git commit -a -m "Updated base images"
            git push
          else
           echo "Nothing changed!"
          fi