name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Matrix:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.set-matrix.outputs.no_build }}
      built_matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Matrix all addons
      id: set-matrix
      run: |
        if [ git --no-pager diff HEAD HEAD~1 --name-only | grep -v -E '^\.' | cut -d'/' -f1 | uniq ]; then
          echo "build=true" >> $GITHUB_OUTPUT
        else
          echo "build=false" >> $GITHUB_OUTPUT
        fi
        output=$(git --no-pager diff HEAD HEAD~1 --name-only | grep -v -E '^\.' | cut -d'/' -f1 | uniq | xargs echo -n | jq -Rsc 'split(" ") | "{ \"addons\": \(.) }"')
        echo "matrix=${output}" >> $GITHUB_OUTPUT

  Build:
    runs-on: ubuntu-latest
    needs: Matrix
    if: needs.Matrix.outputs.build == 'true'
    strategy:
      fail-fast: false
      matrix:
        ${{ insert }}: ${{ fromJson(needs.Matrix.outputs.built_matrix) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
  
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_DEPLOY_KEY }}
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Install yq
      id: perquisite
      run: |
        sudo snap install yq

    - name: Build
      id: build
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        ADDON: ${{ matrix.addons }}
      run: |
        cd ${ADDON}
        VERSION=$(yq -r .version config.yaml)
        docker buildx build \
          --tag "${DOCKER_USER}/${ADDON}:${VERSION}" \
          --platform=linux/arm64,linux/amd64,linux/386,linux/arm/v7,linux/arm/v6 \
          --build-arg "VERSION=${VERSION}" \
          --push \
          -f Dockerfile.buildx .